apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-springboot
spec:
  description: Workshop description.
  session:
    applications:
      docker:
        compose:
          services:
            initializr:
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.1
              ports:
              - mode: host
                protocol: tcp
                published: 8080
                target: 8080
        enabled: true
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
    dashboards:
    - name: Spring Initializr
      url: $(ingress_protocol)://initializr-$(session_hostname)$(ingress_port_suffix)
    ingresses:
    - host: initializr
      name: initializr
      port: 8080
      protocol: http
    namespaces:
      budget: medium
    patches:
      hostAliases:
      - hostnames:
        - initializr
        ip: 127.0.0.1
    resources:
      memory: 2Gi
  title: Workshop
  version: main
  workshop:
    files:
    - image:
        url: ghcr.io/jorgemoralespou/lab-springboot-files:main
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    - image:
        url: ghcr.io/vmware-tanzu-learning/vscode-java-extensions-$(platform_arch)-files:2.1.0
      path: .local/share/code-server/extensions
    image: jdk17-environment:*
